service: serverless

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  profile: serverless-admin
  memorySize: 128
  versionFunctions: false


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
        - "lambda:*"
      Resource:
        - "*"

package:
 exclude:
   - ./**
 include:
   - ./send_mail/**

functions:
  send_mail:
    handler: send_mail/send_mail
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: sendMail
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
